name: Bug
description: Report a defect
title: "[Bug] <short title>"
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What is broken?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
    validations:
      required: true
