name: Story
description: Create a user story for implementation
title: "[Story] <short title>"
labels: ["Story"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Business context and user value
      placeholder: Describe why this story matters
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria (Given/When/Then)
      placeholder: |
        Given ...
        When ...
        Then ...
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes / Dependencies
      description: Technical notes, constraints, dependencies
