name: Task
description: General implementation or maintenance task
title: "[Task] <short title>"
labels: ["Dev"]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      placeholder: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      placeholder: |
        - [ ] Item 1
        - [ ] Item 2
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      placeholder: lint pass, PR review, QA checklist
